### ISSUE TITLE
Something broken in my repos api!

### ISSUE THREAD

**Issue by oianmol** [Anmol92verma/FlutterGithubClient#9]
https://github.com/Anmol92verma/FlutterGithubClient/blob/aa6364b99ed576279b2bc4b70d85606165183b73/lib/network/Github.dart#L150

The url from the log is 

https://api.github.com/user/repos?access_token=access_token=7cec6298b459ef97721150313bb697d7a31d818c&scope=repo%2Cuser&token_type=bearer&visibility=all&affiliation=owner,collaborator,organization_member

**Comment by oianmol** [comment]
@vikram2330 access_token=access_token=7cec6298b459ef97721150313bb697d7a31d818c is asigned twice

**Comment by oianmol** [comment]
Looks like the accessToken saved is prefixed with access_token=

**Comment by oianmol** [comment]
found the issue , it's saved with access_token= . Raising a PR

**Comment by nikhilbansal97** [comment]
@Anmol92verma was this issue fixed?

**Comment by Anmol92verma** [comment]
😂 so you merged it ?

**Comment by oianmol** [comment]
Yes this is fixed ... can you run and check ?
